apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  - apps
  resources:
  - pods
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - extensions.sncloud.com
  resources:
  - podmanagers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
