apiVersion: extensions.sncloud.com/v1alpha1
kind: PodManager
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: grayscale
  namespace: default
spec:
  deploymentName: site
  ipSet:
    - "172.17.0.15"
    - "172.17.0.16"
  strategy:
    type: PodUpgrade
  resources:
    containers:
    - containerName: front-end
      image: redis:latest
